apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/dev
    repoURL: 'https://github.com/gonzaloacosta/kubernetes-devops-spring-rest/'
    targetRevision: HEAD
    kustomize:
      namespace: dev
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
