apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
spec:
  destination:
    name: ''
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/prod
    repoURL: 'git@bitbucket.org:build38.com/kubernetes-devops-spring-rest.git'
    targetRevision: HEAD
    kustomize:
      namespace: prod
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
