apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
spec:
  destination:
    name: ''
    namespace: staging
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/staging
    repoURL: 'https://github.com/gonzaloacosta/kubernetes-devops-spring-rest/'
    targetRevision: HEAD
    kustomize:
      namespace: staging
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
